### ISSUE TITLE
install error with zgen

### ISSUE THREAD

**Issue by chestertonic** [lukechilds/zsh-nvm#1]
When attempting to install with zgen I get:
`Creating a zgen save`
``/home/chester/.zgen/lukechilds/zsh-nvm-master/zsh-nvm.plugin.zsh:65: parse error near `]]'```

**Comment by lukechilds** [comment]
Thanks for reporting this, looking into it now.

**Comment by lukechilds** [comment]
@chestertonic What version of `zsh` are you using?

**Comment by lukechilds** [comment]
@chestertonic This was caused by me doing a truthy check rather than doing a proper check for a string of non-zero length.

Worked for me on zsh 5.1 but I get the same error as you on a fresh Ubuntu vm with zsh 5.0.2.

All sorted now, if you run `zgen update` and then open a new terminal you should be good to go. 👍

**Comment by lukechilds** [comment]
@chestertonic Is this working ok for you now?
